version: "2"
services:
  unleash-db:
    container_name: unleash-db
    image: bitnami/postgresql:12
    environment:
      POSTGRES_DB: "unleash"
      POSTGRES_USER: "unleash"
      POSTGRES_PASSWORD: "unleash"
      DISABLE_WELCOME_MESSAGE: "true"
    ports:
      - "5432:5432"
    networks:
      - unleash
  unleash-test:
    image: unleashorg/unleash-server:3.10.1
    container_name: unleash-test
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: 'postgres://unleash:unleash@unleash-db:5432/unleash'
    networks:
      - unleash

networks:
  unleash: